### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by mjmeans** [ms-iot/iot-controls#2]
Please update the readmen.md file to tell people what this is for, how to use the project and what tools or products are required.

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.

**Comment by saraclay** [comment]
Since this issue was opened a while ago, I will close it if any recent updates have fixed this. For future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs

**Comment by mjmeans** [comment]
The readme.md for THIS repo has not been updated. Someone stumbling upon this repo has no easy way to know what this is for. The name of the repo, "iot-controls" is insufficient because the name is functionally generic.
