### ISSUE TITLE
How to control LCD backlight (USB HID)

### ISSUE THREAD

**Issue by natashasweety7** [ms-iot/iot-controls#3]
we are using the  Chalkboard Electronics 7” LCD Capacitive Touchscreen Display on the board RPi3 with the OS version 10.0.15063.0, I would like to control the LCD backlight using HID commands from a UWP App. It's possible?

thanks in advance
[Natasha](https://mindmajix.com/iot-training)

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.

**Comment by saraclay** [comment]
Since this issue was opened a while ago, I will close it if any recent updates have fixed this. For future issues, please file them at: www.github.com/MicrosoftDocs/windows-iotcore-docs
